import type { Metadata } from "next"
import "./globals.css"
import { poppins } from "@/lib/fonts"
import { Header } from "@/app/components/header"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased text-neutral-800 bg-neutral-200/80`}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
