import type { Metadata } from "next"
import "./globals.css"
import { poppins } from "@/lib/fonts"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
  className?: string
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${poppins.className} antialiased relative text-neutral-800  h-full`}
      >
        {children}
      </body>
    </html>
  )
}
